FROM node:20-alpine AS builder
WORKDIR /app/packages/backend
COPY packages/backend/package.json ./package.json
RUN npm install
COPY packages/backend .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app/packages/backend
COPY --from=builder /app/packages/backend/package.json ./package.json
COPY --from=builder /app/packages/backend/node_modules ./node_modules
COPY --from=builder /app/packages/backend/dist ./dist
EXPOSE 8000
CMD ["npm", "start"]
