FROM node:20-alpine AS builder
WORKDIR /app
COPY pnpm-lock.yaml ./
RUN corepack enable && pnpm install --frozen-lockfile

COPY packages/bot ./packages/bot
WORKDIR /app/packages/bot
RUN pnpm build

FROM node:20-alpine AS runner
WORKDIR /app/packages/bot
COPY --from=builder /app/node_modules ./node_modules
COPY . .
CMD ["pnpm", "start"]
