FROM node:20-slim AS builder
WORKDIR /app/packages/bot
COPY packages/bot/package.json ./package.json
RUN npm install
COPY packages/bot .
RUN npm run build

FROM node:20-slim AS runner
WORKDIR /app/packages/bot
COPY --from=builder /app/packages/bot/package.json ./package.json
COPY --from=builder /app/packages/bot/node_modules ./node_modules
COPY --from=builder /app/packages/bot/dist ./dist
CMD ["npm", "start"]
