import type { Opportunity } from '@/lib/feed/types';

export function getDemoOpportunities(): Opportunity[] {
  const now = Date.now();

  return [
    {
      id: 'demo-1',
      chain: 'EVM',
      ts: now - 900,
      routeId: 'usdc-weth-usdc-uni-sushi',
      routeLabel: 'USDC -> WETH -> USDC',
      venues: ['UniswapV3', 'SushiSwap'],
      tokens: { in: 'USDC', out: 'USDC', mid: ['WETH'] },
      size: { min: 250, max: 5000, unit: 'USDC' },
      profit: {
        grossUsd: 18.4,
        feesUsd: 2.1,
        gasUsd: 6.3,
        slippageUsd: 3.2,
        netUsd: 6.8,
        netBps: 22,
      },
      scores: { confidence: 0.74, mevRisk: 0.42, execProbability: 0.63, volatilityRisk: 0.28 },
      status: 'NEEDS_APPROVAL',
      reasons: ['Token approval required for USDC', 'Two-hop route'],
    },
    {
      id: 'demo-2',
      chain: 'SOL',
      ts: now - 300,
      routeId: 'usdc-sol-usdc-jup-ray',
      routeLabel: 'USDC -> SOL -> USDC',
      venues: ['Jupiter', 'Raydium'],
      tokens: { in: 'USDC', out: 'USDC', mid: ['SOL'] },
      size: { min: 50, max: 2500, unit: 'USDC' },
      profit: {
        grossUsd: 9.2,
        feesUsd: 0.8,
        priorityFeeUsd: 0.2,
        slippageUsd: 1.1,
        netUsd: 7.1,
        netBps: 31,
      },
      scores: { confidence: 0.81, volatilityRisk: 0.22, execProbability: 0.77 },
      status: 'READY',
      reasons: ['Wallet-ready route', 'Low slippage'],
    },
    {
      id: 'demo-3',
      chain: 'EVM',
      ts: now - 8000,
      routeId: 'dai-usdc-curve-uni',
      routeLabel: 'DAI -> USDC -> DAI',
      venues: ['Curve', 'UniswapV3'],
      tokens: { in: 'DAI', out: 'DAI', mid: ['USDC'] },
      size: { min: 500, max: 10000, unit: 'DAI' },
      profit: {
        grossUsd: 15.1,
        feesUsd: 1.4,
        gasUsd: 7.9,
        slippageUsd: 4.9,
        netUsd: 0.9,
        netBps: 2,
      },
      scores: { confidence: 0.48, mevRisk: 0.61, execProbability: 0.21, volatilityRisk: 0.55 },
      status: 'STALE',
      reasons: ['Stale quote', 'Low confidence'],
    },
    {
      id: 'demo-4',
      chain: 'SOL',
      ts: now - 1100,
      routeId: 'bonk-sol-bonk-jupiter',
      routeLabel: 'BONK -> SOL -> BONK',
      venues: ['Jupiter', 'Orca'],
      tokens: { in: 'BONK', out: 'BONK', mid: ['SOL'] },
      size: { min: 150, max: 4000, unit: 'USDC' },
      profit: {
        grossUsd: 11.7,
        feesUsd: 1.1,
        priorityFeeUsd: 0.4,
        slippageUsd: 2.8,
        netUsd: 7.4,
        netBps: 18,
      },
      scores: { confidence: 0.69, volatilityRisk: 0.63, execProbability: 0.58 },
      status: 'HIGH_RISK',
      reasons: ['High token volatility', 'Route size sensitive'],
    },
    {
      id: 'demo-5',
      chain: 'EVM',
      ts: now - 650,
      routeId: 'usdc-arb-usdc-base-bridge',
      routeLabel: 'USDC -> ARB -> USDC',
      venues: ['Camelot', 'Balancer'],
      tokens: { in: 'USDC', out: 'USDC', mid: ['ARB'] },
      size: { min: 80, max: 1800, unit: 'USDC' },
      profit: {
        grossUsd: 5.7,
        feesUsd: 0.9,
        gasUsd: 2.6,
        slippageUsd: 0.8,
        netUsd: 1.4,
        netBps: 9,
      },
      scores: { confidence: 0.67, mevRisk: 0.18, execProbability: 0.72, volatilityRisk: 0.24 },
      status: 'LOW_BALANCE',
      reasons: ['Wallet balance below preferred execution size'],
    },
  ];
}
